steps:
  - run:
      name: Save test results
      command: |
        mkdir -p ~/test-results/junit/
        find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      when: always
  - run: 
      name: Install JUnit coverage reporter
      command: yarn add --dev jest-junit
  - run:
      name: Run tests with JUnit as reporter
      command: jest --ci --runInBand --reporters=default --reporters=jest-junit
      environment:
        JEST_JUNIT_OUTPUT_DIR: ./reports/
      path: ./reports/
  - store_test_results:
      path: ~/test-results

